global:
  scrape_interval: 15s

scrape_configs:

  - job_name: "cadvisor"
    static_configs:
      - targets:
          - "spidersoft-cadvisor:8080"

  - job_name: "spidersoft-api"
    static_configs:
      - targets:
          - "spidersoft-api:5000"
